const LAT_DEFAULT = 35.6894;
const LNG_DEFAULT = 139.692;
const ESC_KEYCODE_TEXT = 'Escape';
const ESC_KEYCODE_SHORT_TEXT = 'Esc';
const MAP_ZOOM = 12;
const PRECISION_NUMBER = 5;

export {LAT_DEFAULT, LNG_DEFAULT, ESC_KEYCODE_TEXT, ESC_KEYCODE_SHORT_TEXT, MAP_ZOOM, PRECISION_NUMBER};
